name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Show repo root and files
        run: |
          echo "Repository root: $(pwd)"
          ls -al

      - name: Build with Maven wrapper (fallback to system mvn)
        run: |
          if [ -f mvnw ]; then
            chmod +x mvnw
            ./mvnw -B package
          elif [ -f pom.xml ]; then
            mvn -B -f pom.xml package
          else
            echo "No mvnw or pom.xml found in the repository root."
            ls -al
            exit 1
          fi
